mainSections = ["posts"]
description = "Coffee Pudding has the answer to everything."

repoURL = "https://github.com/sokuzen/pudding.coffee"
# If it is a Github repo, leave blank
repoEditURL = ""

dateFormat = ""

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType = "Blog"
icon = "icon.png"
publisherName = "Example publisher"
publisherLogo = ""

[hero]
  slogan = '"I always wanted to be a part of a team building things that people love" - Chris Wanstrath'
  # Specify the image name in `assets/images/` folder.
  imgLeft = "images/jess-bailey-Et5Du1dc7kk-unsplash.jpg"
  imgRight = "images/pexels-kaboompics-com-54283.jpg"

[comment]
  # Options: disqus and commento.
#  platform = "disqus"
  platform = ""

  [comment.disqus]
#    shortname = "coffee-pudding"
    shortname = ""

  [comment.commento]
    # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty. 
    url = ""